/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoemPoemIdRouteImport } from './routes/poem/$poemId'
import { Route as ApiOgHomeRouteImport } from './routes/api/og/home'
import { Route as ApiOgPoemIdRouteImport } from './routes/api/og/$poemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoemPoemIdRoute = PoemPoemIdRouteImport.update({
  id: '/poem/$poemId',
  path: '/poem/$poemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgHomeRoute = ApiOgHomeRouteImport.update({
  id: '/api/og/home',
  path: '/api/og/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgPoemIdRoute = ApiOgPoemIdRouteImport.update({
  id: '/api/og/$poemId',
  path: '/api/og/$poemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/poem/$poemId': typeof PoemPoemIdRoute
  '/api/og/$poemId': typeof ApiOgPoemIdRoute
  '/api/og/home': typeof ApiOgHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/poem/$poemId': typeof PoemPoemIdRoute
  '/api/og/$poemId': typeof ApiOgPoemIdRoute
  '/api/og/home': typeof ApiOgHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/poem/$poemId': typeof PoemPoemIdRoute
  '/api/og/$poemId': typeof ApiOgPoemIdRoute
  '/api/og/home': typeof ApiOgHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/poem/$poemId' | '/api/og/$poemId' | '/api/og/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/poem/$poemId' | '/api/og/$poemId' | '/api/og/home'
  id: '__root__' | '/' | '/poem/$poemId' | '/api/og/$poemId' | '/api/og/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoemPoemIdRoute: typeof PoemPoemIdRoute
  ApiOgPoemIdRoute: typeof ApiOgPoemIdRoute
  ApiOgHomeRoute: typeof ApiOgHomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poem/$poemId': {
      id: '/poem/$poemId'
      path: '/poem/$poemId'
      fullPath: '/poem/$poemId'
      preLoaderRoute: typeof PoemPoemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/home': {
      id: '/api/og/home'
      path: '/api/og/home'
      fullPath: '/api/og/home'
      preLoaderRoute: typeof ApiOgHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$poemId': {
      id: '/api/og/$poemId'
      path: '/api/og/$poemId'
      fullPath: '/api/og/$poemId'
      preLoaderRoute: typeof ApiOgPoemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoemPoemIdRoute: PoemPoemIdRoute,
  ApiOgPoemIdRoute: ApiOgPoemIdRoute,
  ApiOgHomeRoute: ApiOgHomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
